Spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/galettes
    username: postgres
    password: Morrigan551!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: daems.aline90@gmail.com
    password: rduvgyvrgmiwxfcn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    protocol: smtp

    test-connection: false

